### ISSUE TITLE
master branch has failing snapshot tests

### ISSUE THREAD

**Issue by darynmitchell** [jobn/braid#71]
Got 2 failed snapshot tests when running `npm run tests` and selecting "run all tests"

- ProjectList, Snapshot name: `ProjectList renders single project according to snapshot 1`
- ProjectContainer, Snapshot name: `ProjectContainer renders fetched and normalized data 1`

Looks like it's just updated styling but snapshot wasn't updated to reflect it?

With no dev guide there's no guarantee I've done all required steps. I just did:
```
npm install
npm run lint #ok
npm run build #ok
npm run test #2 failed tests
```

---

###### Full test results:
```
 FAIL  src/ProjectList.test.js
  ● ProjectList › renders single project according to snapshot

    expect(received).toMatchSnapshot()

    Snapshot name: `ProjectList renders single project according to snapshot 1`

    - Snapshot
    + Received

    @@ -5,11 +5,11 @@
          class="title is-3"
        >
          Select project
        </h1>
        <div
    -     style="display: grid;"
    +     style="display: grid; grid-template-columns: 1fr 1fr 1fr;"
        >
          <a
            class="notification is-primary is-marginless"
            href="/projects/1"
          >

      40 |     );
      41 |
    > 42 |     expect(container.firstChild).toMatchSnapshot();
         |                                  ^
      43 |   });
      44 |
      45 |   it('renders alternating colors', () => {

      at Object.toMatchSnapshot (src/ProjectList.test.js:42:34)

 › 1 snapshot failed.
 PASS  src/Story.test.js
 PASS  src/Filters.test.js
 FAIL  src/ProjectContainer.test.js
  ● ProjectContainer › renders fetched and normalized data

    expect(received).toMatchSnapshot()

    Snapshot name: `ProjectContainer renders fetched and normalized data 1`

    - Snapshot
    + Received

    @@ -146,11 +146,11 @@
                </div>
              </div>
              <span
                class="tag is-warning"
                data-testid="blocked-tag"
    -           style="position: absolute; top: 10px; right: 0px; height: 1.75em; font-size: .65rem; opacity: 1; border-top-right-radius: 0; border-bottom-right-radius: 0;"
    +           style="position: absolute; top: 10px; right: 0px; height: 1.75em; font-size: .65rem; opacity: 1; transition: opacity 1s; border-top-right-radius: 0; border-bottom-right-radius: 0;"
              >
                Blocked
              </span>
            </div>
            <div
    @@ -245,11 +245,11 @@
                </div>
              </div>
              <span
                class="tag is-warning"
                data-testid="blocked-tag"
    -           style="position: absolute; top: 10px; right: 0px; height: 1.75em; font-size: .65rem; opacity: 0; border-top-right-radius: 0; border-bottom-right-radius: 0;"
    +           style="position: absolute; top: 10px; right: 0px; height: 1.75em; font-size: .65rem; opacity: 0; transition: opacity 1s; border-top-right-radius: 0; border-bottom-right-radius: 0;"
              >
                Blocked
              </span>
            </div>
          </div>

      49 |     await wait();
      50 |
    > 51 |     expect(container.firstChild).toMatchSnapshot();
         |                                  ^
      52 |   });
      53 |
      54 |   it('renders error on request error', async () => {

      at Object.toMatchSnapshot (src/ProjectContainer.test.js:51:34)

 › 1 snapshot failed.
 PASS  src/normalize.test.js
 PASS  src/FilterSummary.test.js
 PASS  src/Tray.test.js
 PASS  src/FilterContainer/filters.test.js
 PASS  src/utils/arrayShuffle.test.js
 PASS  src/utils/arrayToggle.test.js
 PASS  src/utils/arrayRotate.test.js

Snapshot Summary
 › 2 snapshots failed from 2 test suites. Inspect your code changes or press `u` to update them.

Test Suites: 2 failed, 9 passed, 11 total
Tests:       2 failed, 61 passed, 63 total
Snapshots:   2 failed, 2 passed, 4 total
Time:        6.546s
Ran all test suites.

```

**Comment by jobn** [comment]
Hi,
I cannot reproduce this. Are you sure you are on a clean master?
the current master does not have `grid-template-columns` anywhere in the code https://github.com/jobn/braid/search?q=grid-template-columns&unscoped_q=grid-template-columns

**Comment by darynmitchell** [comment]
Thanks for trying to repro. Yes, freshly cloned master.

I do see `grid-template-columns` in various node modules.
My first thought if you can't repro is whether you have a previous package.lock. If so, because the repo doesn't contain the package.lock file, my fresh clone could have installed different versions of node modules than what your package.lock froze version numbers at.

If you had an existing package.lock, then a fresh clone + npm install might confirm if this was the cause for no repro.
If not, then I'll have to think of another hypothesis.

**Comment by darynmitchell** [comment]
I can also post the package.lock file that got generated when I npm installed. It will only show version numbers, not whether it causes a repro when someone builds on a fresh clone. But in case it's useful e.g. to make a diff:

[package-lock .json.txt](https://github.com/jobn/braid/files/3633215/package-lock.json.txt)
(renamed to .txt so git will allow the file upload)

**Comment by jobn** [comment]
the reason there is no package-lock file is because i have used yarn in this project. As you can see there is a yarn.lock file. Since it will be a horrible mess to have both yarn.lock and package-lock.json your option here is to use yarn.

If you are not familiar with the commands, here is a quick overview:
https://yarnpkg.com/lang/en/docs/migrating-from-npm/#toc-cli-commands-comparison

Secondly, the generated output in the snapshot is more correct if the packages gets updated. It is quite interesting that the `transition: 'opacity 1s'` which is clearly stated in the styling of the Tag-component does not make it to the test snapshot.  Well, you learn something every day :)

in order to improve the snapshot i am upgrading most of the packages: https://github.com/jobn/braid/pull/72

thank you for highlighting this.

**Comment by darynmitchell** [comment]
Confirmed that yarn install instead of npm install (including nvm to switch node version to one noted as being supported) resulted in all tests passed.
Sorry for the false alarm.

**Comment by jobn** [comment]
👍
