### ISSUE TITLE
Rename columns to reflect pivotal storyState names?

### ISSUE THREAD

**Issue by jobn** [jobn/braid#75]
The current column labels in Braid reflect how we interpret the storyState in the project that I work on, but that might not be the same for everybody.

Should we rename the columns to better reflect the pivotal story states?

| pivotal  | current Braid | Proposal |
|---|---|---|
| unstarted, planned  |  "Planned"  | "Planned"  | 
| started  |  "Started"   | "Started"  |
| finished  |  "Review" | "Finished" |
| delivered, accepted  |  "Accepted \| Done"    |  "Delivered \| Accepted"  |
| delivered  |  "Done"    |  "Delivered"  |
| accepted  |  "Accepted"    |  "Accepted"  |

The argument for changing is to remove the need for mentally mapping the states and make it easier for newcomers to Braid.

Please advise :)

**Comment by jobn** [comment]
@leapingfrogs as the only other known user of Braid, your input on this would be valued greatly

**Comment by jobn** [comment]
this question should also be seen in the light of this pr https://github.com/jobn/braid/pull/76

**Comment by leapingfrogs** [comment]
@jobn - I like this change, we've talked about the names and mappings feeling inconsistent which adds more confusion.

Also just seen the settings to split the final columns, that's a great addition and also helps clarify these states! 👍

**Comment by jobn** [comment]
Thank for the input. I'll merge the pr.
