### ISSUE TITLE
Certain PT projects work and others don't?

### ISSUE THREAD

**Issue by samount** [jobn/braid#78]
Odd issue...out of 10 Pivotal Tracker projects, one does not work. I can navigate through all projects fine, but as soon as I select my Product Development project from either the main menu or the drop down menu, it displays for a brief second and then does not.
Verified in PT that "Allow the Tracker iOS and Android app and other third-party clients to access your project data." is checked.
I am an owner of all projects, using my API token.
The current iteration of the project that does not render using Braid does contain ~77 stories

![Screen Shot 2019-10-08 at 5 37 44 PM](https://user-images.githubusercontent.com/24943249/66443044-635e6980-e9f2-11e9-9e40-9db5271f3a79.png)

**Comment by jobn** [comment]
Interesting :)
Could I get you to look in the browsers console and see any if there is any errors listed there?

**Comment by samount** [comment]
No problem. I see this:
![Screen Shot 2019-10-09 at 10 12 16 AM](https://user-images.githubusercontent.com/24943249/66504101-4c188e00-ea7d-11e9-85da-24ff607a7ada.png)

**Comment by samount** [comment]
Interesting...the first story in the list does have a blocker applied that is a string, not a link to another PT story

**Comment by samount** [comment]
Expanded:

![Screen Shot 2019-10-09 at 10 21 26 AM](https://user-images.githubusercontent.com/24943249/66504713-9b12f300-ea7e-11e9-9c31-db9a85065f0b.png)

**Comment by samount** [comment]
Last update for now...I tested with a test project in PT, added 3 stories, 1 with a blocker that was a string only and did not reference another PT story. It displayed fine, with no errors.

**Comment by jobn** [comment]
the bug seems to be related to blockers referencing unknown stories. It could also be and unhandled race condition.
@samount could I get you to try the failing project in this review-app: https://deploy-preview-79--braid.netlify.com/ and paste the output from the console again?

**Comment by samount** [comment]
@jobn it works using the review-app. Screenshot:

![Screen Shot 2019-10-09 at 1 14 58 PM](https://user-images.githubusercontent.com/24943249/66516854-d9b4a780-ea96-11e9-8e17-45acf72f4636.png)

**Comment by samount** [comment]
@jobn looks like stories with epics as blockers

**Comment by samount** [comment]
Rather releases with epics as blockers

**Comment by jobn** [comment]
@samount so the three stories that are mentioned in the warnings are releases?

**Comment by jobn** [comment]
@samount fix is deployed.

Thanks for the help and feedback :)

**Comment by samount** [comment]
@jobn Wonderful, thank you! I'm using this for standups beginning next week.

**Comment by jobn** [comment]
👍 good luck. Let me know how it goes
